### ISSUE TITLE
Embedding the fonts

### ISSUE THREAD

**Issue by polluks** [tschak909/platotermamiga#9]
Please take a look at my http://aminet.net/package/misc/emu/TI4Amiga
maybe I'll find the source of the font routines...

**Comment by wschaub** [comment]
FontConverter from Fred Fish disk 644 at 
http://ftp.funet.fi/pub/amiga/fish/601-700/ff644/FontConverter.lha

And looks very promising indeed. it has full example code for not only converting font files into C headers but how to use them as well in two working example programs.

The big problem to solve after that is how to dynamically re-define a font in memory for the PLATO fonts that can be uploaded to the terminal from the server side.

**Comment by tschak909** [comment]
Dayumn, that's...pretty beautiful.

-Thom

**Comment by tschak909** [comment]
Yup, this worked.
